# Generated by Django 4.2.8 on 2023-12-26 09:50

from django.db import migrations, models
import validators.fieldvalidators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[validators.fieldvalidators.FieldValidators.iranian_phone_validator, validators.fieldvalidators.FieldValidators.xss_validator], verbose_name='Phone')),
                ('full_name', models.CharField(max_length=255, validators=[validators.fieldvalidators.FieldValidators.xss_validator])),
                ('photo', models.ImageField(upload_to='label')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
