# Generated by Django 4.2.8 on 2023-12-26 09:53

from django.db import migrations, models
import validators.fieldvalidators


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='scan',
            name='last_name',
            field=models.CharField(default='hamid', max_length=255, validators=[validators.fieldvalidators.FieldValidators.xss_validator]),
            preserve_default=False,
        ),
    ]
