# Generated by Django 4.2.8 on 2023-12-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_rename_full_name_scan_first_name_scan_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_part',
            field=models.CharField(choices=[('Load from source', 'بارگیری از مبدا'), ('Delivery to the distribution system', 'تحویل به سیستم توزیع'), ('Delivery to the store', 'تحویل به فروشگاه')], default='LFS', max_length=35),
            preserve_default=False,
        ),
    ]
