# Generated by Django 4.2.8 on 2023-12-26 10:16

from django.db import migrations, models
import validators.fieldvalidators


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_scan_scan_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='phone',
            field=models.CharField(max_length=11, validators=[validators.fieldvalidators.FieldValidators.iranian_phone_validator, validators.fieldvalidators.FieldValidators.xss_validator], verbose_name='Phone'),
        ),
    ]
