# Generated by Django 4.2.8 on 2023-12-26 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_alter_scan_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='manufacture_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='number_in_box',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='product_type',
            field=models.CharField(choices=[('ESL milk', 'ESL شیر'), ('pasteurized Milk', 'شیر پاستوریزه')], default='ESL', max_length=35),
            preserve_default=False,
        ),
    ]
