# Generated by Django 4.2.8 on 2023-12-31 12:59

from django.db import migrations, models
import validators.fieldvalidators


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_scan_manufacture_date_scan_number_in_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='manufacture_date',
            field=models.CharField(max_length=255, validators=[validators.fieldvalidators.FieldValidators.xss_validator]),
        ),
    ]
